### ISSUE TITLE
No module named 'utilities'

### ISSUE THREAD

**Issue by yyf17** [Samarth-Tripathi/IEMOCAP-Emotion-Detection#2]
when I run the file"IEMOCAP-Emotion-Detection-master/code/python_files/Experiments/Untitled.ipynb",
I encounter an error as follows:

```
ImportError                               Traceback (most recent call last)
<ipython-input-7-77e3842cda67> in <module>()
     25 sys.path.append("/data/disk2/sharing/IEMOCAP_full_release/")
     26 
---> 27 from utilities.utils import *
     28 
     29 import matplotlib

ImportError: No module named 'utilities'
```
I have searched on the internet,but there is no correct package named 'utilities'.
How can I solve the problem?
my email: yyf17@mails.tsinghua.edu.cn

**Comment by Samarth-Tripathi** [comment]
Please use this code for utilities, in the code folder. Do let me know if you encounter any other problems.

https://github.com/vladimir-chernykh/emotion_recognition/tree/master/code/utilities

Thanks for letting me know!!

Regards,
Samarth
