### ISSUE TITLE
where is the PDF and PPT

### ISSUE THREAD

**Issue by ChenJiaDong9219** [Samarth-Tripathi/IEMOCAP-Emotion-Detection#3]
hello, I've seen your README mentioned that there are PDF and PPT, but didn't see them.

**Comment by Samarth-Tripathi** [comment]
https://arxiv.org/abs/1804.05788

Please cite this if you use the code

**Comment by ChenJiaDong9219** [comment]
thanks !

**Comment by ChenJiaDong9219** [comment]
@Samarth-Tripathi thanks !
