### ISSUE TITLE
utilities folder

### ISSUE THREAD

**Issue by f785735155** [Samarth-Tripathi/IEMOCAP-Emotion-Detection#4]
Hello Samarth Tripathi:
                                    Hello, I don't quite understand what the utilities folder means. Because you are using a MAC system, and I am using a WIN system? How to convert or use it?

**Comment by Samarth-Tripathi** [comment]
https://github.com/Samarth-Tripathi/IEMOCAP-Emotion-Detection/issues/2#issue-339130465

you just download the utilities folder in the code folder. It has python libraries of acoustic speech processing that the code uses. Not an OS issue.

**Comment by f785735155** [comment]
Where should I put after I download the utilities folder? Also need to process the data set after downloading? I put IEMOCAP_full_release.tar directly in the data folder.

**Comment by Samarth-Tripathi** [comment]
inside the code/python_files folder itself. 
data needs to be extracted and put into the data folder inside a new session folder.

Run mocap_data_collect.py and debug if some path based problems, should be straightforward

**Comment by f785735155** [comment]
Thank you! I have run successfully.
