### ISSUE TITLE
Keras version problem

### ISSUE THREAD

**Issue by f785735155** [Samarth-Tripathi/IEMOCAP-Emotion-Detection#5]
Hello, when I run speech, Tmport_Error:connot import name '_time_distributed_dence' occurs, I was used keras2.1.0 and 1.2.0. But it was useless. Which version were you used?

**Comment by bagustris** [comment]
I tried with Keras==2.0.8, and it works until the last line for Speech.ipynb

**Comment by f785735155** [comment]
Thank you
