### ISSUE TITLE
question about input

### ISSUE THREAD

**Issue by smkim0220** [Samarth-Tripathi/IEMOCAP-Emotion-Detection#6]
how do I create data_collected.pickle??
I have IEMOCAP raw data and I want to create pickle and run your code

**Comment by Samarth-Tripathi** [comment]
Run mocap_data_collect.py
it would create data_collected.pickle

**Comment by smkim0220** [comment]
Thanks!! I created pickle. 
Would it be possible to know about prerequisite(versions of modules)?

**Comment by dangvansam** [comment]
where are data file (wav files)? i cant run file mocap_data_collect.py dont have folder /data/sessions/Session1/dialog/wav/

**Comment by Samarth-Tripathi** [comment]
please download the dataset first.

**Comment by Samarth-Tripathi** [comment]
@smkim0220  refer to issue #5

**Comment by dangvansam** [comment]
i have data with 5 session folder  in Sentences folder i want to get wav files but it havent  labeled by name of emotion. how to decode and category them by text in EmoEvaluation folder

**Comment by dangvansam** [comment]
[Ses01F_impro01.txt](https://github.com/Samarth-Tripathi/IEMOCAP-Emotion-Detection/files/2672327/Ses01F_impro01.txt)


[Ses01F_impro01.zip](https://github.com/Samarth-Tripathi/IEMOCAP-Emotion-Detection/files/2672335/Ses01F_impro01.zip)
2 file how to match emotionn and wav file thanks
