### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by hermione3** [Samarth-Tripathi/IEMOCAP-Emotion-Detection#8]
Hello Sir! 
I have run your codes successfully and also plotted graphs for them but I'm having a tough time in understanding feature extraction. I would be really grateful to you if you could please provide some help in the feature extraction methods used. I'm just a beginner hence any help would be appreciated. Thank You in advance!

**Comment by Samarth-Tripathi** [comment]
Feel free to use https://arxiv.org/abs/1804.05788 for more information, and cite it if you do.
Most of the feature extraction especially for speech based models is standard, you should be able to find enough resources on the internet after referring the paper.
